<?php

// all possible options will be stored
$config = array();

// a unique key that identifies this application - DO NOT LEAVE THIS EMPTY!
$config['app_key'] = '4fb91e8dc11c03ce1617b2eca62f2969';

// a secret key to be used during encryption
$config['encryption_key'] = '';

// URL running the proxy app
//$config['app_url'] = 'https://www.mysampleproxy.com/proxyfolder/';

/*
how unique is each URL that is generated by this proxy app?
0 - no encoding of any sort. People can link to proxy pages directly: ?q=http://www.yahoo.com // Tanpa enkripsi
1 - Base64 encoding only, people can hotlink to your proxy // Link enkripsi yang dicopy di beda browser/device akan sama
2 - unique to the IP address that generated it. A person that generated that URL, can bookmark it and visit it and any point  // Link enkripsi tidak bisa dicopy 
3 - unique to that session and IP address - URL no longer valid anywhere when that browser session that generated it ends
*/

$config['url_mode'] = 2;

// plugins to load - plugins will be loaded in this exact order as in array
$config['plugins'] = array(
	'HeaderRewrite',
	'Stream',
	// ^^ do not disable any of the plugins above
	'Cookie',
	'Proxify',
	'UrlForm',
);

// additional curl options to go with each request
//$url = '';
//$proxy = '';
//$proxyauth = 'user:password';



$config['curl'] = array(
	
	//CURLOPT_PROXY => $proxy,
	//CURLOPT_CONNECTTIMEOUT => 5
);

//$config['replace_title'] = 'Google Search';

//$config['error_redirect'] = "https://unblockvideos.com/#error={error_msg}";
//$config['index_redirect'] = 'https://unblockvideos.com/';

// $config['replace_icon'] = 'icon_url';

// this better be here other Config::load fails
return $config;

?>
